// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void come_out_Animation(lv_obj_t * TargetObject, int delay);
void move_left_Animation(lv_obj_t * TargetObject, int delay);
void APP_focus_Animation(lv_obj_t * TargetObject, int delay);
void APP_XL_Animation(lv_obj_t * TargetObject, int delay);
void APP_XR_Animation(lv_obj_t * TargetObject, int delay);
void opa_Animation(lv_obj_t * TargetObject, int delay);
void APP_YUP_Animation(lv_obj_t * TargetObject, int delay);
void APP_YDown_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_Label1(lv_event_t * e);
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image1;
void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Panel2(lv_event_t * e);
// extern lv_obj_t * app_weather;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_817053662);    // assets\彩虹.png
LV_IMG_DECLARE(ui_img_1888405804);    // assets\微风.png
LV_IMG_DECLARE(ui_img_749799162);    // assets\晴转阴.png
LV_IMG_DECLARE(ui_img_1838330290);    // assets\雷阵雨.png
LV_IMG_DECLARE(ui_img_thinking_256x256_png);    // assets\thinking_256x256.png

LV_FONT_DECLARE(ui_font_Arcade80);
LV_FONT_DECLARE(ui_font_Point50);
LV_FONT_DECLARE(ui_font_Point70);
LV_FONT_DECLARE(ui_font_cat70);
LV_FONT_DECLARE(ui_font_mont80);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
